name: contexts
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    env: 
      ACTOR: ${{ github.actor }}
    steps:
      - run: echo "run workflow by ${ACTOR}"
      - run: echo "runner os is ${RUNNER_OS}"