name: contexts
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      run: 
        - echo "run workflow by ${{ github.actor }}"
        - echo "runner os is ${{ runner.os }}"